name: Docs

on:
  push:
    branches:
      - master

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-docs:
    name: Update docs on Github Pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.5.1]
        julia-arch: [x86]
        os: [ubuntu-latest]

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - name: Build, deploy and upload docs
        run: | 
          julia --project=docs -e 'using Pkg; Pkg.instantiate()'
          julia --project=docs --color=yes docs/make.jl
        env:
          REPO: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git
          DEVBRANCH: master

