name: Release

on:
  push:
    branches:
      - release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: [1.5.1]
        julia-arch: [x86]
        os: [ubuntu-latest]

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}

      - name: Install dependencies
        run: --project=docs -e 'using Pkg; Pkg.instantiate()'

      - name: Build, deploy and upload docs
        run: julia --project=docs --color=yes docs/make.jl
        env:
          REPO: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git

      - name: Fetch project version
        run: |
          VERSION = `cat Project.toml | grep "version" | cut -d '=' -f2 | tr -d ' ' `
          echo $VERSION
      #- name: Create a new Github Release
